module.exports = {
  GRAPHQL_ERROR: {
    BAD_USER_INPUT: 'BAD_USER_INPUT',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_OPERATION: 'INVALID_OPERATION'
  }
};
